[tool.black]
line-length = 150
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded by ^/ will apply only to files and directories
# in the root of the project.
(
  ^/data/.*\.py$      # exclude generated data files
  | migrations/.*     # exclude migrations
)
'''

[tool.isort]
profile = "black"
line_length = 150
